### ISSUE TITLE
first_name and last_name empty

### ISSUE THREAD

**Issue by sehmaschine** [workos/workos-python#123]
I'Ve recently updated to workos 1.11.0 and now I don't get `first_name` and `last_name` anymore (they are both empty within `profile`). The claims are defined correctly and the SAML Response Body (Azure AD) includes `givenname` and `surname`. A couple of weeks ago it worked – not sure what has changed here and it might also be an error on my side (but as said before, we did not change anything and the setup is correct according to the setuplink given with workos).

**Comment by maxdeviant** [comment]
Hey there @sehmaschine, did you start seeing these issues immediately after upgrading your SDK version? What version did you upgrade from?

We’ll need to figure out if this is an issue with the SDK or with the actual Connection in WorkOS.

For help with the latter, if you haven’t already you can reach out to support@workos.com and our Developer Success team can look into it for you. If you have a shared Slack channel with us you can reach out there too.

**Comment by maxdeviant** [comment]
Going to close this out, for now.

Feel free to reopen if this is still an issue.
