### ISSUE TITLE
ConnectionType enums are not valid in `has_value()`

### ISSUE THREAD

**Issue by joetheone** [workos/workos-python#144]
Hello,

I used to have some code that looked like this:

    authorization_url = workos_client.sso.get_authorization_url(
        provider=ConnectionType.GoogleOAuth,
        redirect_uri=f'{API_HOST}/v1/sso/finish/',
    )

Everything worked well until I updated to from 1.14.0 to 1.15.0.

Now I get the following error: `ValueError: 'provider' must be of type ConnectionType`

This is because `ConnectionType.has_value(ConnectionType.GoogleOAuth)` is False.
Using `ConnectionType.has_value('GoogleOAuth')` works, but it seems like a worse practice than what I had before.

**Comment by bryanbanda** [comment]
Yup, definitely looks like a regression and a worse off practice

**Comment by maxdeviant** [comment]
Thanks for reporting this! This is definitely a regression in the SDK.

It looks like @bryanbanda has a PR up that fixes the issue, so we'll be looking to get that merged soon.

**Comment by maxdeviant** [comment]
This has been addressed in https://github.com/workos/workos/pull/19909 and released in [v1.19.0](https://github.com/workos/workos-python/pull/157).
