### ISSUE TITLE
Support type checking

### ISSUE THREAD

**Issue by Saare** [workos/workos-python#145]
Hey :)

The Python SDK does not currently support type checking, causing mypy to display `Skipping analyzing "workos": module is installed, but missing library stubs or py.typed marker  [import]`.
It's probably not high on your list of priorities but I figured it should be mentioned anyway :)

https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

**Comment by maxdeviant** [comment]
Thanks for the suggestion! We'll see where this fits on our roadmap for the Python SDK.
