### ISSUE TITLE
setting api_key on workos instead of workos_client ?

### ISSUE THREAD

**Issue by NgyAnthony** [workos/workos-python#168]
Hi there,

I'm using workos v1.21.0 on python 3.8.16 with fastapi 0.89.1

I've been following this guide:

https://workos.com/docs/magic-link/1-add-magic-link-to-your-app/create-a-passwordless-session-and-email-the-user

And noticed that to add the api_key and client _id we need to do:
```
from workos import client as workos_client

workos_client.api_key = "123"
workos_client.client_id = "123"
```

I haven't been able to add my api keys this way and instead had to do:
```
import workos

workos.api_key = "123"
workos.client_id = "123"
```

If you view the following lines https://github.com/workos/workos-python/blob/9f9a90a6bb4982cf0f34e6039f842c5a57f69aa2/workos/utils/validation.py#L44-L52

You'll see that `getattr` is done on `workos` directly (which has the api_key and client_id) https://github.com/workos/workos-python/blob/c337704900fa6698e7cfc1f172104717aae8ecdf/workos/__init__.py#L6-L7

So I'm wondering if I'm doing something wrong or if it's an issue with the docs

**Comment by maxdeviant** [comment]
The Docs have been updated to align with the SDK:

<img width="1389" alt="Screen Shot 2023-04-06 at 12 56 51 PM" src="https://user-images.githubusercontent.com/1486634/230445581-9cca52d3-711c-4437-8acc-d7312349f7e8.png">
