### ISSUE TITLE
missing string formatting 

### ISSUE THREAD

**Issue by yehuda-margolis** [workos/workos-python#252]
https://github.com/workos/workos-python/blob/a145e1200ff200317dd292177cbfc5e40cb0cc64/workos/mfa.py#L138

The authentication_factor_id argument is sent as is (string) instead of the argument's actual value

**Comment by amadeo-workos** [comment]
https://github.com/workos/workos-python/pull/254

**Comment by amadeo-workos** [comment]
This has been fixed, and included in the v4.3.1 release: https://github.com/workos/workos-python/releases/tag/v4.3.1

Closing this issue now.
