### ISSUE TITLE
Invalid logout URL

### ISSUE THREAD

**Issue by abingham** [workos/workos-python#269]
The URL produced by `UserManagement.get_logout_url()` seems to be incorrect. It's producing "https://api.workos.com//user_management/sessions/logout?session_id=...", i.e. with two forward slashes after "api.workos.com". This should be a single forward slash, shouldn't it?

It looks like this could be fixed most easily by changing `workos.base_api_url` from "https://api.workos.com/" to ""https://api.workos.com". This would fix what looks like a similar problem in `UserManagement.get_jwks_url()`.

**Comment by abingham** [comment]
It looks like I was hasty about my suggested fix. Users of `workos.utils.request.RequestHelper` rely on the `base_api_url` having a trailing slash. The alternatives seem to be either:

1. Remove the trailing slash from `base_api_url` and update users of `RequestHelper` to not expect a trailing slash.
2. Leave `base_api_url` alone and update `get_logout_url()` and `get_jwks_url()` to expect a trailing slash. (Maybe these should even be using `RequestHelper` somehow.

**Comment by PaulAsjes** [comment]
Yikes sorry about that, we'll get that fixed today.

**Comment by PaulAsjes** [comment]
I went with option 2 to get a quick fix out, but I agree that we should revisit how these work and perhaps use `RequestHelper`.

**Comment by abingham** [comment]
Thanks for the quick resolution! Do you know when there will be a new release of the package with this fix?

**Comment by PaulAsjes** [comment]
Just released as v4.8.0 :)
