### ISSUE TITLE
Wrong docs for get_authorization_url

### ISSUE THREAD

**Issue by hyperknot** [workos/workos-python#315]
Docs says:
https://workos.com/docs/reference/user-management/authentication/get-authorization-url

> If you are using AuthKit, set the provider parameter to "authkit", which will generate an authorization URL for your AuthKit domain.

This doesn't work, it needs to be 

```
    authorization_url = client.user_management.get_authorization_url(
        provider=UserManagementProviderType.AuthKit,
        redirect_uri='http://localhost:3000/callback',
    )
```

Only way to figure this out is to dig into source code.

**Comment by PaulAsjes** [comment]
Hey there, this is now fixed in v5 of the SDK. The following will now work as expected:
```python
authorization_url = client.user_management.get_authorization_url(
    provider='authkit',
    redirect_uri='http://localhost:3000/callback',
)
```
