### ISSUE TITLE
Mismatch in create organization doc and how actually to pass method arguments

### ISSUE THREAD

**Issue by FilipAtScribe** [workos/workos-python#371]
There is a mismatch in how `organization_create` takes parameters and how it is described in the docs:
https://workos.com/docs/reference/organization/create
The actual way of passing the new_organization would be unpacked as kwargs
so not as new_organization but as **new_organization

**Comment by mattgd** [comment]
Hey @FilipAtScribe, thanks for catching this. We'll have a fix up shortly.

**Comment by mattgd** [comment]
This has been updated, thanks again!
