### ISSUE TITLE
list_organizations ignores limit argument

### ISSUE THREAD

**Issue by chrismaeda** [workos/workos-python#391]
- I have 18 organizations in my staging environment.
- When I call list_organizations(limit=10), it always returns 18 organizations
- Update: I also see the same behavior in list_events

Environment:
- Python 3.10.12
- workos 5.10.0
- Ubuntu 22.04.5 LTS

Program 1:

```
def test_list_organizations_asc(workos_client: WorkOSClient):
    orgs_dict = {}
    after = None
    limit = 10    
    while True:
        print(f"Fetch {limit} Organizations after={after}")
        orgs = workos_client.organizations.list_organizations(limit=10, after=after, order='asc')
        fetchcount = 0
        for org in orgs:
            print(f"Org: {org.name} {org.id}  Created At: {org.created_at}")
            fetchcount += 1
            if org.name in orgs_dict:
                print (f"WARN: Organization {org.name} already exists")
                continue
            orgs_dict[org.name] = org
        print(f"Fetched {fetchcount} Organizations")
        metadata = orgs.list_metadata
        if metadata:
            after = metadata.after
        if not after:
            break
    return orgs_dict
```

Printed Output:
Fetch 10 Organizations after=None
Org: Test Organization org_01J9A2XE4NAP3HYSRWPGZ67XYN  Created At: 2024-10-03T21:00:00.346Z
Org: AgencyTest org_01J9A2YVN2Z6R8EQDYGB6Z7BM4  Created At: 2024-10-03T21:00:47.650Z
Org: Botco Demo org_01JD0WXTSX1QHTWS0HWDBHYNFZ  Created At: 2024-11-19T00:24:59.965Z
Org: Account Zero org_01JEAY8SHMJM99BTJX457DHYXQ  Created At: 2024-12-05T08:16:33.843Z
Org: DEFAULT org_01JEAY95X83BSGTV4QAPKAJTYW  Created At: 2024-12-05T08:16:46.504Z
Org: bwrbot org_01JEAYA1YAFQPEN0MY39NCYJPA  Created At: 2024-12-05T08:17:15.209Z
Org: massageenvy org_01JEAYAE5S03FH0G55RGHNPCW8  Created At: 2024-12-05T08:17:27.736Z
Org: bottega org_01JEAYAQTBPXG2GKCTF2B20ASW  Created At: 2024-12-05T08:17:37.610Z
Org: cmaeda test account org_01JEAYBGKAH9FTZBBWQGAHWS52  Created At: 2024-12-05T08:18:02.986Z
Org: webchat development org_01JEAYC1MCWC48AKGKED2MYT40  Created At: 2024-12-05T08:18:20.427Z
Org: ChatLogTool Unit Test org_01JEAYCV4XE6F799GX98NPAJA2  Created At: 2024-12-05T08:18:46.557Z
Org: Prod Regression Tests org_01JEAYDBQVDHDCW3M1E60NG74H  Created At: 2024-12-05T08:19:03.547Z
Org: Tooljet Test 1 org_01JEAYE3WDKZZDHK85R3PKNR35  Created At: 2024-12-05T08:19:28.268Z
Org: Tooljet Test 2 org_01JEAYEH5XX8SY85QAFTWW344Z  Created At: 2024-12-05T08:19:41.884Z
Org: Tooljet Test 3 org_01JEAYEWXPR86VFKWBJQK9KX0F  Created At: 2024-12-05T08:19:53.909Z
Org: Tooljet Test 4 org_01JEAYFACXKZ86JV09HEQTKGNR  Created At: 2024-12-05T08:20:07.709Z
Org: Tooljet Test 5 org_01JEAYFN8PCSSQVR0NA7ZVV4R5  Created At: 2024-12-05T08:20:18.837Z
Org: HomerSoft org_01JEAYFZ7PZ9DJR9GQYW5EVFFV  Created At: 2024-12-05T08:20:29.045Z
Fetched 18 Organizations
Fetch 10 Organizations after=org_01JEAYC1MCWC48AKGKED2MYT40
Org: ChatLogTool Unit Test org_01JEAYCV4XE6F799GX98NPAJA2  Created At: 2024-12-05T08:18:46.557Z
WARN: Organization ChatLogTool Unit Test already exists
Org: Prod Regression Tests org_01JEAYDBQVDHDCW3M1E60NG74H  Created At: 2024-12-05T08:19:03.547Z
WARN: Organization Prod Regression Tests already exists
Org: Tooljet Test 1 org_01JEAYE3WDKZZDHK85R3PKNR35  Created At: 2024-12-05T08:19:28.268Z
WARN: Organization Tooljet Test 1 already exists
Org: Tooljet Test 2 org_01JEAYEH5XX8SY85QAFTWW344Z  Created At: 2024-12-05T08:19:41.884Z
WARN: Organization Tooljet Test 2 already exists
Org: Tooljet Test 3 org_01JEAYEWXPR86VFKWBJQK9KX0F  Created At: 2024-12-05T08:19:53.909Z
WARN: Organization Tooljet Test 3 already exists
Org: Tooljet Test 4 org_01JEAYFACXKZ86JV09HEQTKGNR  Created At: 2024-12-05T08:20:07.709Z
WARN: Organization Tooljet Test 4 already exists
Org: Tooljet Test 5 org_01JEAYFN8PCSSQVR0NA7ZVV4R5  Created At: 2024-12-05T08:20:18.837Z
WARN: Organization Tooljet Test 5 already exists
Org: HomerSoft org_01JEAYFZ7PZ9DJR9GQYW5EVFFV  Created At: 2024-12-05T08:20:29.045Z
WARN: Organization HomerSoft already exists
Fetched 8 Organizations

Program 2:

```
def test_list_organizations_desc(workos_client: WorkOSClient):
    orgs_dict = {}
    after = None
    limit = 10
    while True:
        print(f"Fetch {limit} Organizations after={after}")
        orgs = workos_client.organizations.list_organizations(limit=10, after=after, order='desc')
        fetchcount = 0
        for org in orgs:
            print(f"Org: {org.name} {org.id}  Created At: {org.created_at}")
            fetchcount += 1
            if org.name in orgs_dict:
                print (f"WARN: Organization {org.name} already exists")
                continue
            orgs_dict[org.name] = org
        print(f"Fetched {fetchcount} Organizations")
        metadata = orgs.list_metadata
        if metadata:
            after = metadata.after
        if not after:
            break
    return orgs_dict
```

Printed Output:

Fetch 10 Organizations after=None
Org: HomerSoft org_01JEAYFZ7PZ9DJR9GQYW5EVFFV  Created At: 2024-12-05T08:20:29.045Z
Org: Tooljet Test 5 org_01JEAYFN8PCSSQVR0NA7ZVV4R5  Created At: 2024-12-05T08:20:18.837Z
Org: Tooljet Test 4 org_01JEAYFACXKZ86JV09HEQTKGNR  Created At: 2024-12-05T08:20:07.709Z
Org: Tooljet Test 3 org_01JEAYEWXPR86VFKWBJQK9KX0F  Created At: 2024-12-05T08:19:53.909Z
Org: Tooljet Test 2 org_01JEAYEH5XX8SY85QAFTWW344Z  Created At: 2024-12-05T08:19:41.884Z
Org: Tooljet Test 1 org_01JEAYE3WDKZZDHK85R3PKNR35  Created At: 2024-12-05T08:19:28.268Z
Org: Prod Regression Tests org_01JEAYDBQVDHDCW3M1E60NG74H  Created At: 2024-12-05T08:19:03.547Z
Org: ChatLogTool Unit Test org_01JEAYCV4XE6F799GX98NPAJA2  Created At: 2024-12-05T08:18:46.557Z
Org: webchat development org_01JEAYC1MCWC48AKGKED2MYT40  Created At: 2024-12-05T08:18:20.427Z
Org: cmaeda test account org_01JEAYBGKAH9FTZBBWQGAHWS52  Created At: 2024-12-05T08:18:02.986Z
Org: bottega org_01JEAYAQTBPXG2GKCTF2B20ASW  Created At: 2024-12-05T08:17:37.610Z
Org: massageenvy org_01JEAYAE5S03FH0G55RGHNPCW8  Created At: 2024-12-05T08:17:27.736Z
Org: bwrbot org_01JEAYA1YAFQPEN0MY39NCYJPA  Created At: 2024-12-05T08:17:15.209Z
Org: DEFAULT org_01JEAY95X83BSGTV4QAPKAJTYW  Created At: 2024-12-05T08:16:46.504Z
Org: Account Zero org_01JEAY8SHMJM99BTJX457DHYXQ  Created At: 2024-12-05T08:16:33.843Z
Org: Botco Demo org_01JD0WXTSX1QHTWS0HWDBHYNFZ  Created At: 2024-11-19T00:24:59.965Z
Org: AgencyTest org_01J9A2YVN2Z6R8EQDYGB6Z7BM4  Created At: 2024-10-03T21:00:47.650Z
Org: Test Organization org_01J9A2XE4NAP3HYSRWPGZ67XYN  Created At: 2024-10-03T21:00:00.346Z
Fetched 18 Organizations
Fetch 10 Organizations after=org_01JEAYBGKAH9FTZBBWQGAHWS52
Org: bottega org_01JEAYAQTBPXG2GKCTF2B20ASW  Created At: 2024-12-05T08:17:37.610Z
WARN: Organization bottega already exists
Org: massageenvy org_01JEAYAE5S03FH0G55RGHNPCW8  Created At: 2024-12-05T08:17:27.736Z
WARN: Organization massageenvy already exists
Org: bwrbot org_01JEAYA1YAFQPEN0MY39NCYJPA  Created At: 2024-12-05T08:17:15.209Z
WARN: Organization bwrbot already exists
Org: DEFAULT org_01JEAY95X83BSGTV4QAPKAJTYW  Created At: 2024-12-05T08:16:46.504Z
WARN: Organization DEFAULT already exists
Org: Account Zero org_01JEAY8SHMJM99BTJX457DHYXQ  Created At: 2024-12-05T08:16:33.843Z
WARN: Organization Account Zero already exists
Org: Botco Demo org_01JD0WXTSX1QHTWS0HWDBHYNFZ  Created At: 2024-11-19T00:24:59.965Z
WARN: Organization Botco Demo already exists
Org: AgencyTest org_01J9A2YVN2Z6R8EQDYGB6Z7BM4  Created At: 2024-10-03T21:00:47.650Z
WARN: Organization AgencyTest already exists
Org: Test Organization org_01J9A2XE4NAP3HYSRWPGZ67XYN  Created At: 2024-10-03T21:00:00.346Z
WARN: Organization Test Organization already exists
Fetched 8 Organizations

**Comment by PaulAsjes** [comment]
Hey there, this is working as expected since you're triggering the auto-paginator by iterating over the response:

```
for org in orgs:
```

If you remove that loop and just print the `orgs` you'll find that it returned the amount of orgs specified in your `limit`.
